print("This is example for File Handling in python")
print("****** START- FILE HANDLING ********")
f=open("pogo.txt",'w')
print("File Name : ",f.name)
print("File Mode: ",f.mode)
print("Is FIle is Redable: ",f.readable())
print("Is FIle is Writable: ",f.writable())
print("Is File is Closed: ",f.closed)
f.close()
print("Is File is Closed: ",f.closed)